spring:
  application:
    name: eWallet

  datasource:
    url: jdbc:postgresql://localhost:5432/eWallet
    username: eWalletUser
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true